ALTER TABLE IF EXISTS "agg_champion_bucket"
  ADD COLUMN IF NOT EXISTS "sum_time_played" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sum_kills" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sum_assists" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sum_deaths" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sum_kills_assists" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sum_kd_diff_10" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sum_kd_diff_20" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "count_kd_diff_10_positive_game" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "count_kd_diff_10_positive_win" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "count_kd_diff_20_positive_game" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "count_kd_diff_20_positive_win" BIGINT NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS "archive_agg_champion_bucket"
  ADD COLUMN IF NOT EXISTS "sum_time_played" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sum_kills" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sum_assists" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sum_deaths" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sum_kills_assists" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sum_kd_diff_10" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sum_kd_diff_20" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "count_kd_diff_10_positive_game" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "count_kd_diff_10_positive_win" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "count_kd_diff_20_positive_game" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "count_kd_diff_20_positive_win" BIGINT NOT NULL DEFAULT 0;
