DO $$
DECLARE
  target_table text;
  spec text;
  col_name text;
  col_type text;
  specs text[] := ARRAY[
    'sum_12_assist_streak_count:bigint',
    'sum_heal_from_map_sources:double precision',
    'sum_infernal_scale_pickup:bigint',
    'sum_aces_before_15_minutes:bigint',
    'sum_allied_jungle_monster_kills:bigint',
    'sum_baron_takedowns:bigint',
    'sum_blast_cone_opposite_opponent_count:bigint',
    'sum_buffs_stolen:bigint',
    'sum_complete_support_quest_in_time:bigint',
    'sum_deaths_by_enemy_champs:bigint',
    'sum_dodge_skill_shots_small_window:bigint',
    'sum_double_aces:bigint',
    'sum_dragon_takedowns:bigint',
    'sum_earliest_baron:double precision',
    'sum_elder_dragon_kills_with_opposing_soul:bigint',
    'sum_elder_dragon_multikills:bigint',
    'sum_enemy_champion_immobilizations:bigint',
    'sum_enemy_jungle_monster_kills:bigint',
    'sum_epic_monster_kills_near_enemy_jungler:bigint',
    'sum_epic_monster_kills_within_30_seconds_of_spawn:bigint',
    'sum_epic_monster_steals:bigint',
    'sum_epic_monster_stolen_without_smite:bigint',
    'sum_first_turret_killed:bigint',
    'sum_first_turret_killed_time:double precision',
    'sum_fist_bump_participation:bigint',
    'sum_had_open_nexus:bigint',
    'sum_immobilize_and_kill_with_ally:bigint',
    'sum_initial_buff_count:bigint',
    'sum_initial_crab_count:bigint',
    'sum_jungle_cs_before_10_minutes:bigint',
    'sum_jungler_takedowns_near_damaged_epic_monster:bigint',
    'sum_k_turrets_destroyed_before_plates_fall:bigint',
    'sum_kill_after_hidden_with_ally:bigint',
    'sum_kill_participation:double precision',
    'sum_killed_champ_took_full_team_damage_survived:bigint',
    'sum_kills_near_enemy_turret:bigint',
    'sum_kills_on_other_lanes_early_jungle_as_laner:bigint',
    'sum_kills_on_recently_healed_by_aram_pack:bigint',
    'sum_kills_under_own_turret:bigint',
    'sum_kills_with_help_from_epic_monster:bigint',
    'sum_knock_enemy_into_team_and_kill:bigint',
    'sum_multi_kill_one_spell:bigint',
    'sum_multi_turret_rift_herald_count:bigint',
    'sum_multikills:bigint',
    'sum_multikills_after_aggressive_flash:bigint',
    'sum_outer_turret_executes_before_10_minutes:bigint',
    'sum_outnumbered_kills:bigint',
    'sum_perfect_dragon_souls_taken:bigint',
    'sum_perfect_game:bigint',
    'sum_pick_kill_with_ally:bigint',
    'sum_quick_cleanse:bigint',
    'sum_quick_first_turret:bigint',
    'sum_quick_solo_kills:bigint',
    'sum_rift_herald_takedowns:bigint',
    'sum_save_ally_from_death:bigint',
    'sum_scuttle_crab_kills:bigint',
    'sum_skillshots_dodged:bigint',
    'sum_skillshots_hit:bigint',
    'sum_solo_baron_kills:bigint',
    'sum_solo_kills:bigint',
    'sum_solo_turrets_lategame:bigint',
    'sum_stealth_wards_placed:bigint',
    'sum_survived_single_digit_hp_count:bigint',
    'sum_survived_three_immobilizes_in_fight:bigint',
    'sum_takedown_on_first_turret:bigint',
    'sum_takedowns:bigint',
    'sum_takedowns_after_gaining_level_advantage:bigint',
    'sum_takedowns_before_jungle_minion_spawn:bigint',
    'sum_takedowns_first_x_minutes:bigint',
    'sum_takedowns_in_alcove:bigint',
    'sum_takedowns_in_enemy_fountain:bigint',
    'sum_team_baron_kills:bigint',
    'sum_team_elder_dragon_kills:bigint',
    'sum_team_rift_herald_kills:bigint',
    'sum_took_large_damage_survived:bigint',
    'sum_turret_plates_taken:bigint',
    'sum_turrets_taken_with_rift_herald:bigint',
    'sum_twenty_minions_in_3_seconds_count:bigint',
    'sum_two_wards_one_sweeper_count:bigint',
    'sum_unseen_recalls:bigint',
    'sum_void_monster_kill:bigint',
    'sum_ward_takedowns:bigint',
    'sum_ward_takedowns_before_20_m:bigint',
    'sum_wards_guarded:bigint',
    'sum_command_pings:bigint',
    'sum_consumables_purchased:bigint',
    'sum_danger_pings:bigint',
    'sum_detector_wards_placed:bigint',
    'sum_double_kills:bigint',
    'sum_dragon_kills:bigint',
    'sum_enemy_missing_pings:bigint',
    'sum_enemy_vision_pings:bigint',
    'count_first_blood_assist_false:bigint',
    'count_first_blood_kill_false:bigint',
    'count_first_tower_assist_false:bigint',
    'count_first_tower_kill_false:bigint',
    'sum_get_back_pings:bigint',
    'sum_hold_pings:bigint',
    'sum_inhibitor_kills:bigint',
    'sum_inhibitor_takedowns:bigint',
    'sum_inhibitors_lost:bigint',
    'sum_items_purchased:bigint',
    'sum_largest_killing_spree:bigint',
    'sum_largest_multi_kill:bigint',
    'sum_longest_time_spent_living:bigint',
    'sum_need_vision_pings:bigint',
    'sum_neutral_minions_killed:bigint',
    'count_nexus_kills:bigint',
    'sum_nexus_takedowns:bigint',
    'sum_objectives_stolen:bigint',
    'sum_objectives_stolen_assists:bigint',
    'sum_on_my_way_pings:bigint',
    'sum_penta_kills:bigint',
    'sum_quadra_kills:bigint',
    'sum_retreat_pings:bigint',
    'sum_sight_wards_bought_in_game:bigint',
    'sum_time_ccing_others:bigint',
    'sum_total_ally_jungle_minions_killed:bigint',
    'sum_total_time_spent_dead:bigint',
    'sum_triple_kills:bigint',
    'sum_turret_kills:bigint',
    'sum_turrets_lost:bigint',
    'sum_unreal_kills:bigint',
    'sum_vision_cleared_pings:bigint',
    'sum_vision_wards_bought_in_game:bigint'
  ];
BEGIN
  FOREACH target_table IN ARRAY ARRAY['agg_champion_participant_stats', 'archive_agg_champion_participant_stats']
  LOOP
    FOREACH spec IN ARRAY specs
    LOOP
      col_name := split_part(spec, ':', 1);
      col_type := split_part(spec, ':', 2);
      EXECUTE format(
        'ALTER TABLE IF EXISTS %I ADD COLUMN IF NOT EXISTS %I %s NOT NULL DEFAULT 0',
        target_table,
        col_name,
        col_type
      );
    END LOOP;
  END LOOP;
END $$;
