ALTER TABLE tracked_matches
  ADD COLUMN IF NOT EXISTS player1 JSONB,
  ADD COLUMN IF NOT EXISTS player2 JSONB,
  ADD COLUMN IF NOT EXISTS player3 JSONB,
  ADD COLUMN IF NOT EXISTS player4 JSONB,
  ADD COLUMN IF NOT EXISTS player5 JSONB,
  ADD COLUMN IF NOT EXISTS player6 JSONB,
  ADD COLUMN IF NOT EXISTS player7 JSONB,
  ADD COLUMN IF NOT EXISTS player8 JSONB,
  ADD COLUMN IF NOT EXISTS player9 JSONB,
  ADD COLUMN IF NOT EXISTS player10 JSONB;
