-- Replace participant_challenges key/value table with one column per allowlisted challenge on participants.
-- challenge_keys_registry is kept for new-key discovery.
-- 1) Add columns 2) Backfill from participant_challenges 3) Drop table.

ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_solo_kills DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_takedowns DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_bounty_gold DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_double_aces DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_buffs_stolen DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_flawless_aces DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_had_open_nexus DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_quick_cleanse DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_snowballs_hit DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_wards_guarded DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_earliest_baron DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_skillshots_hit DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_unseen_recalls DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_max_kill_deficit DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_quick_solo_kills DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_solo_baron_kills DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_void_monster_kill DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_full_team_takedown DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_initial_buff_count DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_initial_crab_count DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_outnumbered_kills DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_pick_kill_with_ally DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_quick_first_turret DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_scuttle_crab_kills DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_skillshots_dodged DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_multi_kill_one_spell DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_save_ally_from_death DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_takedowns_in_alcove DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_turret_plates_taken DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_heal_from_map_sources DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_12_assist_streak_count DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_infernal_scale_pickup DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_aces_before_15_minutes DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_deaths_by_enemy_champs DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_kills_under_own_turret DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_rift_herald_takedowns DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_team_rift_herald_kills DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_kills_near_enemy_turret DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_team_elder_dragon_kills DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_elder_dragon_multikills DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_first_turret_killed_time DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_fist_bump_participation DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_mejais_full_stack_in_time DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_takedown_on_first_turret DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_takedowns_first_x_minutes DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_ward_takedowns_before_20_m DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_jungle_cs_before_10_minutes DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_kill_after_hidden_with_ally DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_land_skill_shots_early_game DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_perfect_dragon_souls_taken DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_took_large_damage_survived DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_two_wards_one_sweeper_count DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_max_level_lead_lane_opponent DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_takedowns_in_enemy_fountain DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_immobilize_and_kill_with_ally DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_knock_enemy_into_team_and_kill DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_lane_minions_first_10_minutes DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_played_champ_select_position DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_complete_support_quest_in_time DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_dodge_skill_shots_small_window DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_multi_turret_rift_herald_count DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_survived_single_digit_hp_count DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_turrets_taken_with_rift_herald DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_laning_phase_gold_exp_advantage DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_more_enemy_jungle_than_opponent DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_enemy_champion_immobilizations DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_kills_with_help_from_epic_monster DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_max_cs_advantage_on_lane_opponent DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_twenty_minions_in_3_seconds_count DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_epic_monster_stolen_without_smite DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_blast_cone_opposite_opponent_count DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_multikills_after_aggressive_flash DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_survived_three_immobilizes_in_fight DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_early_laning_phase_gold_exp_advantage DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_elder_dragon_kills_with_opposing_soul DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_epic_monster_kills_near_enemy_jungler DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_takedowns_before_jungle_minion_spawn DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_vision_score_advantage_lane_opponent DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_outer_turret_executes_before_10_minutes DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_baron_buff_gold_advantage_over_threshold DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_kills_on_other_lanes_early_jungle_as_laner DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_takedowns_after_gaining_level_advantage DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_killed_champ_took_full_team_damage_survived DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_epic_monster_kills_within_30_seconds_of_spawn DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_jungler_takedowns_near_damaged_epic_monster DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_get_takedowns_in_all_lanes_early_jungle_as_laner DOUBLE PRECISION NULL;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS ch_control_ward_time_coverage_in_river_or_enemy_half DOUBLE PRECISION NULL;


UPDATE participants p SET ch_solo_kills = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'soloKills';
UPDATE participants p SET ch_takedowns = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'takedowns';
UPDATE participants p SET ch_bounty_gold = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'bountyGold';
UPDATE participants p SET ch_double_aces = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'doubleAces';
UPDATE participants p SET ch_buffs_stolen = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'buffsStolen';
UPDATE participants p SET ch_flawless_aces = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'flawlessAces';
UPDATE participants p SET ch_had_open_nexus = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'hadOpenNexus';
UPDATE participants p SET ch_quick_cleanse = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'quickCleanse';
UPDATE participants p SET ch_snowballs_hit = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'snowballsHit';
UPDATE participants p SET ch_wards_guarded = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'wardsGuarded';
UPDATE participants p SET ch_earliest_baron = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'earliestBaron';
UPDATE participants p SET ch_skillshots_hit = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'skillshotsHit';
UPDATE participants p SET ch_unseen_recalls = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'unseenRecalls';
UPDATE participants p SET ch_max_kill_deficit = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'maxKillDeficit';
UPDATE participants p SET ch_quick_solo_kills = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'quickSoloKills';
UPDATE participants p SET ch_solo_baron_kills = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'soloBaronKills';
UPDATE participants p SET ch_void_monster_kill = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'voidMonsterKill';
UPDATE participants p SET ch_full_team_takedown = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'fullTeamTakedown';
UPDATE participants p SET ch_initial_buff_count = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'initialBuffCount';
UPDATE participants p SET ch_initial_crab_count = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'initialCrabCount';
UPDATE participants p SET ch_outnumbered_kills = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'outnumberedKills';
UPDATE participants p SET ch_pick_kill_with_ally = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'pickKillWithAlly';
UPDATE participants p SET ch_quick_first_turret = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'quickFirstTurret';
UPDATE participants p SET ch_scuttle_crab_kills = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'scuttleCrabKills';
UPDATE participants p SET ch_skillshots_dodged = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'skillshotsDodged';
UPDATE participants p SET ch_multi_kill_one_spell = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'multiKillOneSpell';
UPDATE participants p SET ch_save_ally_from_death = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'saveAllyFromDeath';
UPDATE participants p SET ch_takedowns_in_alcove = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'takedownsInAlcove';
UPDATE participants p SET ch_turret_plates_taken = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'turretPlatesTaken';
UPDATE participants p SET ch_heal_from_map_sources = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'HealFromMapSources';
UPDATE participants p SET ch_12_assist_streak_count = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = '12AssistStreakCount';
UPDATE participants p SET ch_infernal_scale_pickup = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'InfernalScalePickup';
UPDATE participants p SET ch_aces_before_15_minutes = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'acesBefore15Minutes';
UPDATE participants p SET ch_deaths_by_enemy_champs = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'deathsByEnemyChamps';
UPDATE participants p SET ch_kills_under_own_turret = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'killsUnderOwnTurret';
UPDATE participants p SET ch_rift_herald_takedowns = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'riftHeraldTakedowns';
UPDATE participants p SET ch_team_rift_herald_kills = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'teamRiftHeraldKills';
UPDATE participants p SET ch_kills_near_enemy_turret = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'killsNearEnemyTurret';
UPDATE participants p SET ch_team_elder_dragon_kills = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'teamElderDragonKills';
UPDATE participants p SET ch_elder_dragon_multikills = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'elderDragonMultikills';
UPDATE participants p SET ch_first_turret_killed_time = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'firstTurretKilledTime';
UPDATE participants p SET ch_fist_bump_participation = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'fistBumpParticipation';
UPDATE participants p SET ch_mejais_full_stack_in_time = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'mejaisFullStackInTime';
UPDATE participants p SET ch_takedown_on_first_turret = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'takedownOnFirstTurret';
UPDATE participants p SET ch_takedowns_first_x_minutes = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'takedownsFirstXMinutes';
UPDATE participants p SET ch_ward_takedowns_before_20_m = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'wardTakedownsBefore20M';
UPDATE participants p SET ch_jungle_cs_before_10_minutes = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'jungleCsBefore10Minutes';
UPDATE participants p SET ch_kill_after_hidden_with_ally = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'killAfterHiddenWithAlly';
UPDATE participants p SET ch_land_skill_shots_early_game = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'landSkillShotsEarlyGame';
UPDATE participants p SET ch_perfect_dragon_souls_taken = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'perfectDragonSoulsTaken';
UPDATE participants p SET ch_took_large_damage_survived = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'tookLargeDamageSurvived';
UPDATE participants p SET ch_two_wards_one_sweeper_count = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'twoWardsOneSweeperCount';
UPDATE participants p SET ch_max_level_lead_lane_opponent = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'maxLevelLeadLaneOpponent';
UPDATE participants p SET ch_takedowns_in_enemy_fountain = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'takedownsInEnemyFountain';
UPDATE participants p SET ch_immobilize_and_kill_with_ally = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'immobilizeAndKillWithAlly';
UPDATE participants p SET ch_knock_enemy_into_team_and_kill = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'knockEnemyIntoTeamAndKill';
UPDATE participants p SET ch_lane_minions_first_10_minutes = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'laneMinionsFirst10Minutes';
UPDATE participants p SET ch_played_champ_select_position = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'playedChampSelectPosition';
UPDATE participants p SET ch_complete_support_quest_in_time = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'completeSupportQuestInTime';
UPDATE participants p SET ch_dodge_skill_shots_small_window = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'dodgeSkillShotsSmallWindow';
UPDATE participants p SET ch_multi_turret_rift_herald_count = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'multiTurretRiftHeraldCount';
UPDATE participants p SET ch_survived_single_digit_hp_count = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'survivedSingleDigitHpCount';
UPDATE participants p SET ch_turrets_taken_with_rift_herald = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'turretsTakenWithRiftHerald';
UPDATE participants p SET ch_laning_phase_gold_exp_advantage = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'laningPhaseGoldExpAdvantage';
UPDATE participants p SET ch_more_enemy_jungle_than_opponent = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'moreEnemyJungleThanOpponent';
UPDATE participants p SET ch_enemy_champion_immobilizations = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'enemyChampionImmobilizations';
UPDATE participants p SET ch_kills_with_help_from_epic_monster = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'killsWithHelpFromEpicMonster';
UPDATE participants p SET ch_max_cs_advantage_on_lane_opponent = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'maxCsAdvantageOnLaneOpponent';
UPDATE participants p SET ch_twenty_minions_in_3_seconds_count = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'twentyMinionsIn3SecondsCount';
UPDATE participants p SET ch_epic_monster_stolen_without_smite = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'epicMonsterStolenWithoutSmite';
UPDATE participants p SET ch_blast_cone_opposite_opponent_count = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'blastConeOppositeOpponentCount';
UPDATE participants p SET ch_multikills_after_aggressive_flash = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'multikillsAfterAggressiveFlash';
UPDATE participants p SET ch_survived_three_immobilizes_in_fight = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'survivedThreeImmobilizesInFight';
UPDATE participants p SET ch_early_laning_phase_gold_exp_advantage = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'earlyLaningPhaseGoldExpAdvantage';
UPDATE participants p SET ch_elder_dragon_kills_with_opposing_soul = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'elderDragonKillsWithOpposingSoul';
UPDATE participants p SET ch_epic_monster_kills_near_enemy_jungler = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'epicMonsterKillsNearEnemyJungler';
UPDATE participants p SET ch_takedowns_before_jungle_minion_spawn = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'takedownsBeforeJungleMinionSpawn';
UPDATE participants p SET ch_vision_score_advantage_lane_opponent = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'visionScoreAdvantageLaneOpponent';
UPDATE participants p SET ch_outer_turret_executes_before_10_minutes = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'outerTurretExecutesBefore10Minutes';
UPDATE participants p SET ch_baron_buff_gold_advantage_over_threshold = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'baronBuffGoldAdvantageOverThreshold';
UPDATE participants p SET ch_kills_on_other_lanes_early_jungle_as_laner = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'killsOnOtherLanesEarlyJungleAsLaner';
UPDATE participants p SET ch_takedowns_after_gaining_level_advantage = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'takedownsAfterGainingLevelAdvantage';
UPDATE participants p SET ch_killed_champ_took_full_team_damage_survived = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'killedChampTookFullTeamDamageSurvived';
UPDATE participants p SET ch_epic_monster_kills_within_30_seconds_of_spawn = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'epicMonsterKillsWithin30SecondsOfSpawn';
UPDATE participants p SET ch_jungler_takedowns_near_damaged_epic_monster = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'junglerTakedownsNearDamagedEpicMonster';
UPDATE participants p SET ch_get_takedowns_in_all_lanes_early_jungle_as_laner = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'getTakedownsInAllLanesEarlyJungleAsLaner';
UPDATE participants p SET ch_control_ward_time_coverage_in_river_or_enemy_half = pc.value FROM participant_challenges pc WHERE pc.participant_id = p.id AND pc.key = 'controlWardTimeCoverageInRiverOrEnemyHalf';

DROP TABLE IF EXISTS participant_challenges CASCADE;
