ALTER TABLE IF EXISTS agg_champion_core_stats
  ADD COLUMN IF NOT EXISTS sum_gold_earned BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sum_gold_spent BIGINT NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS archive_agg_champion_core_stats
  ADD COLUMN IF NOT EXISTS sum_gold_earned BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sum_gold_spent BIGINT NOT NULL DEFAULT 0;
