-- Tables normalisées match (ingestion poller → agrégats). Données conservées (pas de purge).

CREATE TABLE IF NOT EXISTS match_aggregated (
  riot_match_id TEXT PRIMARY KEY,
  aggregated BOOLEAN NOT NULL DEFAULT FALSE,
  aggregated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_match_aggregated_pending
  ON match_aggregated (aggregated)
  WHERE aggregated = FALSE;

CREATE TABLE IF NOT EXISTS matchs (
  patch TEXT NOT NULL,
  riot_match_id TEXT PRIMARY KEY,
  region TEXT NOT NULL,
  queue_id INTEGER NOT NULL DEFAULT 0,
  game_date DATE NOT NULL,
  early_surrender BOOLEAN NOT NULL DEFAULT FALSE,
  surrender BOOLEAN NOT NULL DEFAULT FALSE,
  game_duration INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_matchs_patch_game_date ON matchs (patch, game_date);
CREATE INDEX IF NOT EXISTS idx_matchs_region ON matchs (region);

CREATE TABLE IF NOT EXISTS teams (
  riot_match_id TEXT NOT NULL REFERENCES matchs (riot_match_id) ON DELETE CASCADE,
  team_id INTEGER NOT NULL,
  win BOOLEAN NOT NULL DEFAULT FALSE,
  first_blood BOOLEAN NOT NULL DEFAULT FALSE,
  champion_kills INTEGER NOT NULL DEFAULT 0,
  baron_first BOOLEAN NOT NULL DEFAULT FALSE,
  baron_kills INTEGER NOT NULL DEFAULT 0,
  dragon_first BOOLEAN NOT NULL DEFAULT FALSE,
  dragon_kills INTEGER NOT NULL DEFAULT 0,
  tower_first BOOLEAN NOT NULL DEFAULT FALSE,
  tower_kills INTEGER NOT NULL DEFAULT 0,
  horde_first BOOLEAN NOT NULL DEFAULT FALSE,
  horde_kills INTEGER NOT NULL DEFAULT 0,
  rift_herald_first BOOLEAN NOT NULL DEFAULT FALSE,
  rift_herald_kills INTEGER NOT NULL DEFAULT 0,
  inhibitor_first BOOLEAN NOT NULL DEFAULT FALSE,
  inhibitor_kills INTEGER NOT NULL DEFAULT 0,
  elder_drake_first BOOLEAN NOT NULL DEFAULT FALSE,
  earth_drake_kills INTEGER NOT NULL DEFAULT 0,
  hextec_drake_kills INTEGER NOT NULL DEFAULT 0,
  fire_drake_kills INTEGER NOT NULL DEFAULT 0,
  wind_drake_kills INTEGER NOT NULL DEFAULT 0,
  water_drake_kills INTEGER NOT NULL DEFAULT 0,
  elder_drake_kills INTEGER NOT NULL DEFAULT 0,
  chem_drake_kills INTEGER NOT NULL DEFAULT 0,
  have_soul BOOLEAN NOT NULL DEFAULT FALSE,
  soul_type TEXT,
  objective_outcome_histogram JSONB NOT NULL DEFAULT '[]',
  PRIMARY KEY (riot_match_id, team_id)
);

CREATE TABLE IF NOT EXISTS participants (
  riot_match_id TEXT NOT NULL REFERENCES matchs (riot_match_id) ON DELETE CASCADE,
  participant_id INTEGER NOT NULL,
  puuid VARCHAR(78),
  riot_id_game_name TEXT,
  riot_id_tagline TEXT,
  team_id INTEGER NOT NULL,
  team_position TEXT,
  id_champion_ban INTEGER NOT NULL DEFAULT 0,
  all_in_pings INTEGER NOT NULL DEFAULT 0,
  assist_me_pings INTEGER NOT NULL DEFAULT 0,
  assists INTEGER NOT NULL DEFAULT 0,
  baron_kills INTEGER NOT NULL DEFAULT 0,
  basic_pings INTEGER NOT NULL DEFAULT 0,
  assist_streak_count INTEGER NOT NULL DEFAULT 0,
  heal_from_map_sources DOUBLE PRECISION NOT NULL DEFAULT 0,
  infernal_scale_pickup INTEGER NOT NULL DEFAULT 0,
  ability_uses INTEGER NOT NULL DEFAULT 0,
  aces_before_15_minutes INTEGER NOT NULL DEFAULT 0,
  baron_takedowns INTEGER NOT NULL DEFAULT 0,
  blast_cone_opposite_opponent_count INTEGER NOT NULL DEFAULT 0,
  bounty_gold INTEGER NOT NULL DEFAULT 0,
  buffs_stolen INTEGER NOT NULL DEFAULT 0,
  complete_support_quest_in_time INTEGER NOT NULL DEFAULT 0,
  control_wards_placed INTEGER NOT NULL DEFAULT 0,
  deaths_by_enemy_champs INTEGER NOT NULL DEFAULT 0,
  dodge_skill_shots_small_window INTEGER NOT NULL DEFAULT 0,
  double_aces INTEGER NOT NULL DEFAULT 0,
  dragon_takedowns INTEGER NOT NULL DEFAULT 0,
  earliest_baron BIGINT NOT NULL DEFAULT 0,
  early_laning_phase_gold_exp_advantage DOUBLE PRECISION NOT NULL DEFAULT 0,
  effective_heal_and_shielding DOUBLE PRECISION NOT NULL DEFAULT 0,
  elder_dragon_kills_with_opposing_soul INTEGER NOT NULL DEFAULT 0,
  elder_dragon_multikills INTEGER NOT NULL DEFAULT 0,
  enemy_champion_immobilizations INTEGER NOT NULL DEFAULT 0,
  epic_monster_kills_near_enemy_jungler INTEGER NOT NULL DEFAULT 0,
  epic_monster_kills_within_30_seconds_of_spawn INTEGER NOT NULL DEFAULT 0,
  epic_monster_steals INTEGER NOT NULL DEFAULT 0,
  epic_monster_stolen_without_smite INTEGER NOT NULL DEFAULT 0,
  first_turret_killed INTEGER NOT NULL DEFAULT 0,
  first_turret_killed_time BIGINT NOT NULL DEFAULT 0,
  flawless_aces INTEGER NOT NULL DEFAULT 0,
  full_team_takedown INTEGER NOT NULL DEFAULT 0,
  get_takedowns_in_all_lanes_early_jungle_as_laner INTEGER NOT NULL DEFAULT 0,
  had_open_nexus INTEGER NOT NULL DEFAULT 0,
  immobilize_and_kill_with_ally INTEGER NOT NULL DEFAULT 0,
  initial_buff_count INTEGER NOT NULL DEFAULT 0,
  initial_crab_count INTEGER NOT NULL DEFAULT 0,
  jungle_cs_before_10_minutes INTEGER NOT NULL DEFAULT 0,
  jungler_takedowns_near_damaged_epic_monster INTEGER NOT NULL DEFAULT 0,
  kill_after_hidden_with_ally INTEGER NOT NULL DEFAULT 0,
  killed_champ_took_full_team_damage_survived INTEGER NOT NULL DEFAULT 0,
  killing_sprees INTEGER NOT NULL DEFAULT 0,
  kills_near_enemy_turret INTEGER NOT NULL DEFAULT 0,
  kills_on_other_lanes_early_jungle_as_laner INTEGER NOT NULL DEFAULT 0,
  kills_under_own_turret INTEGER NOT NULL DEFAULT 0,
  kills_with_help_from_epic_monster INTEGER NOT NULL DEFAULT 0,
  knock_enemy_into_team_and_kill INTEGER NOT NULL DEFAULT 0,
  land_skill_shots_early_game INTEGER NOT NULL DEFAULT 0,
  lane_minions_first_10_minutes INTEGER NOT NULL DEFAULT 0,
  laning_phase_gold_exp_advantage DOUBLE PRECISION NOT NULL DEFAULT 0,
  lost_an_inhibitor BOOLEAN NOT NULL DEFAULT FALSE,
  max_cs_advantage_on_lane_opponent INTEGER NOT NULL DEFAULT 0,
  max_kill_deficit INTEGER NOT NULL DEFAULT 0,
  max_level_lead_lane_opponent INTEGER NOT NULL DEFAULT 0,
  mejais_full_stack_in_time BOOLEAN NOT NULL DEFAULT FALSE,
  more_enemy_jungle_than_opponent INTEGER NOT NULL DEFAULT 0,
  multi_kill_one_spell INTEGER NOT NULL DEFAULT 0,
  multi_turret_rift_herald_count INTEGER NOT NULL DEFAULT 0,
  multikills INTEGER NOT NULL DEFAULT 0,
  multikills_after_aggressive_flash INTEGER NOT NULL DEFAULT 0,
  outer_turret_executes_before_10_minutes INTEGER NOT NULL DEFAULT 0,
  outnumbered_kills INTEGER NOT NULL DEFAULT 0,
  outnumbered_nexus_kill INTEGER NOT NULL DEFAULT 0,
  perfect_dragon_souls_taken BOOLEAN NOT NULL DEFAULT FALSE,
  perfect_game BOOLEAN NOT NULL DEFAULT FALSE,
  pick_kill_with_ally INTEGER NOT NULL DEFAULT 0,
  played_champ_select_position INTEGER NOT NULL DEFAULT 0,
  quick_cleanse INTEGER NOT NULL DEFAULT 0,
  quick_first_turret BOOLEAN NOT NULL DEFAULT FALSE,
  quick_solo_kills INTEGER NOT NULL DEFAULT 0,
  rift_herald_takedowns INTEGER NOT NULL DEFAULT 0,
  save_ally_from_death INTEGER NOT NULL DEFAULT 0,
  scuttle_crab_kills INTEGER NOT NULL DEFAULT 0,
  skillshots_dodged INTEGER NOT NULL DEFAULT 0,
  skillshots_hit INTEGER NOT NULL DEFAULT 0,
  solo_baron_kills INTEGER NOT NULL DEFAULT 0,
  solo_kills INTEGER NOT NULL DEFAULT 0,
  solo_turrets_lategame INTEGER NOT NULL DEFAULT 0,
  stealth_wards_placed INTEGER NOT NULL DEFAULT 0,
  survived_single_digit_hp_count INTEGER NOT NULL DEFAULT 0,
  survived_three_immobilizes_in_fight INTEGER NOT NULL DEFAULT 0,
  takedown_on_first_turret INTEGER NOT NULL DEFAULT 0,
  takedowns INTEGER NOT NULL DEFAULT 0,
  takedowns_after_gaining_level_advantage INTEGER NOT NULL DEFAULT 0,
  takedowns_before_jungle_minion_spawn INTEGER NOT NULL DEFAULT 0,
  takedowns_first_x_minutes INTEGER NOT NULL DEFAULT 0,
  takedowns_in_alcove INTEGER NOT NULL DEFAULT 0,
  takedowns_in_enemy_fountain INTEGER NOT NULL DEFAULT 0,
  took_large_damage_survived INTEGER NOT NULL DEFAULT 0,
  turret_plates_taken INTEGER NOT NULL DEFAULT 0,
  turrets_taken_with_rift_herald INTEGER NOT NULL DEFAULT 0,
  two_wards_one_sweeper_count INTEGER NOT NULL DEFAULT 0,
  unseen_recalls INTEGER NOT NULL DEFAULT 0,
  vision_score_advantage_lane_opponent DOUBLE PRECISION NOT NULL DEFAULT 0,
  void_monster_kill INTEGER NOT NULL DEFAULT 0,
  ward_takedowns INTEGER NOT NULL DEFAULT 0,
  ward_takedowns_before_20m INTEGER NOT NULL DEFAULT 0,
  wards_guarded INTEGER NOT NULL DEFAULT 0,
  champ_experience INTEGER NOT NULL DEFAULT 0,
  champ_level INTEGER NOT NULL DEFAULT 0,
  champion_id INTEGER NOT NULL,
  champion_transform INTEGER NOT NULL DEFAULT 0,
  transform_timestamp_ms BIGINT NOT NULL DEFAULT 0,
  command_pings INTEGER NOT NULL DEFAULT 0,
  consumables_purchased INTEGER NOT NULL DEFAULT 0,
  damage_dealt_to_buildings INTEGER NOT NULL DEFAULT 0,
  damage_dealt_to_epic_monsters INTEGER NOT NULL DEFAULT 0,
  damage_dealt_to_objectives INTEGER NOT NULL DEFAULT 0,
  damage_dealt_to_turrets INTEGER NOT NULL DEFAULT 0,
  danger_pings INTEGER NOT NULL DEFAULT 0,
  deaths INTEGER NOT NULL DEFAULT 0,
  detector_wards_placed INTEGER NOT NULL DEFAULT 0,
  double_kills INTEGER NOT NULL DEFAULT 0,
  dragon_kills INTEGER NOT NULL DEFAULT 0,
  enemy_missing_pings INTEGER NOT NULL DEFAULT 0,
  enemy_vision_pings INTEGER NOT NULL DEFAULT 0,
  first_blood_assist BOOLEAN NOT NULL DEFAULT FALSE,
  first_blood_kill BOOLEAN NOT NULL DEFAULT FALSE,
  first_tower_assist BOOLEAN NOT NULL DEFAULT FALSE,
  first_tower_kill BOOLEAN NOT NULL DEFAULT FALSE,
  get_back_pings INTEGER NOT NULL DEFAULT 0,
  gold_earned INTEGER NOT NULL DEFAULT 0,
  gold_spent INTEGER NOT NULL DEFAULT 0,
  hold_pings INTEGER NOT NULL DEFAULT 0,
  inhibitor_kills INTEGER NOT NULL DEFAULT 0,
  inhibitor_takedowns INTEGER NOT NULL DEFAULT 0,
  inhibitors_lost INTEGER NOT NULL DEFAULT 0,
  kills INTEGER NOT NULL DEFAULT 0,
  largest_critical_strike INTEGER NOT NULL DEFAULT 0,
  largest_killing_spree INTEGER NOT NULL DEFAULT 0,
  largest_multi_kill INTEGER NOT NULL DEFAULT 0,
  longest_time_spent_living INTEGER NOT NULL DEFAULT 0,
  magic_damage_dealt INTEGER NOT NULL DEFAULT 0,
  need_vision_pings INTEGER NOT NULL DEFAULT 0,
  neutral_minions_killed INTEGER NOT NULL DEFAULT 0,
  nexus_kills INTEGER NOT NULL DEFAULT 0,
  nexus_takedowns INTEGER NOT NULL DEFAULT 0,
  objectives_stolen INTEGER NOT NULL DEFAULT 0,
  objectives_stolen_assists INTEGER NOT NULL DEFAULT 0,
  on_my_way_pings INTEGER NOT NULL DEFAULT 0,
  penta_kills INTEGER NOT NULL DEFAULT 0,
  defense_perk_id INTEGER NOT NULL DEFAULT 0,
  flex_perk_id INTEGER NOT NULL DEFAULT 0,
  offense_perk_id INTEGER NOT NULL DEFAULT 0,
  primary_style INTEGER NOT NULL DEFAULT 0,
  primary_selection_0 INTEGER[] NOT NULL DEFAULT '{}',
  primary_selection_1 INTEGER[] NOT NULL DEFAULT '{}',
  primary_selection_2 INTEGER[] NOT NULL DEFAULT '{}',
  primary_selection_3 INTEGER[] NOT NULL DEFAULT '{}',
  secondary_style INTEGER NOT NULL DEFAULT 0,
  secondary_selection_1 INTEGER[] NOT NULL DEFAULT '{}',
  secondary_selection_2 INTEGER[] NOT NULL DEFAULT '{}',
  physical_damage_dealt INTEGER NOT NULL DEFAULT 0,
  push_pings INTEGER NOT NULL DEFAULT 0,
  quadra_kills INTEGER NOT NULL DEFAULT 0,
  retreat_pings INTEGER NOT NULL DEFAULT 0,
  spell1_casts INTEGER NOT NULL DEFAULT 0,
  spell2_casts INTEGER NOT NULL DEFAULT 0,
  spell3_casts INTEGER NOT NULL DEFAULT 0,
  spell4_casts INTEGER NOT NULL DEFAULT 0,
  summoner1_casts INTEGER NOT NULL DEFAULT 0,
  summoner1_id INTEGER NOT NULL DEFAULT 0,
  summoner2_casts INTEGER NOT NULL DEFAULT 0,
  summoner2_id INTEGER NOT NULL DEFAULT 0,
  time_ccing_others INTEGER NOT NULL DEFAULT 0,
  time_played INTEGER NOT NULL DEFAULT 0,
  total_ally_jungle_minions_killed INTEGER NOT NULL DEFAULT 0,
  total_damage_shielded_on_teammates INTEGER NOT NULL DEFAULT 0,
  total_enemy_jungle_minions_killed INTEGER NOT NULL DEFAULT 0,
  total_heal INTEGER NOT NULL DEFAULT 0,
  total_heals_on_teammates INTEGER NOT NULL DEFAULT 0,
  total_minions_killed INTEGER NOT NULL DEFAULT 0,
  total_time_cc_dealt INTEGER NOT NULL DEFAULT 0,
  total_time_spent_dead INTEGER NOT NULL DEFAULT 0,
  total_units_healed INTEGER NOT NULL DEFAULT 0,
  triple_kills INTEGER NOT NULL DEFAULT 0,
  true_damage_dealt INTEGER NOT NULL DEFAULT 0,
  turret_kills INTEGER NOT NULL DEFAULT 0,
  turret_takedowns INTEGER NOT NULL DEFAULT 0,
  turrets_lost INTEGER NOT NULL DEFAULT 0,
  vision_cleared_pings INTEGER NOT NULL DEFAULT 0,
  vision_wards_bought_in_game INTEGER NOT NULL DEFAULT 0,
  wards_killed INTEGER NOT NULL DEFAULT 0,
  wards_placed INTEGER NOT NULL DEFAULT 0,
  item_history JSONB NOT NULL DEFAULT '{}',
  spell_history JSONB NOT NULL DEFAULT '{}',
  death_by_dive INTEGER NOT NULL DEFAULT 0,
  kill_by_dive INTEGER NOT NULL DEFAULT 0,
  kill_by_gank INTEGER NOT NULL DEFAULT 0,
  death_by_gank INTEGER NOT NULL DEFAULT 0,
  kill_by_roaming INTEGER NOT NULL DEFAULT 0,
  death_by_roaming INTEGER NOT NULL DEFAULT 0,
  kill_on_objective INTEGER NOT NULL DEFAULT 0,
  death_on_objective INTEGER NOT NULL DEFAULT 0,
  death_history JSONB NOT NULL DEFAULT '[]',
  kill_history JSONB NOT NULL DEFAULT '[]',
  assist_history JSONB NOT NULL DEFAULT '[]',
  ward_history JSONB NOT NULL DEFAULT '[]',
  gold_buckets INTEGER[] NOT NULL DEFAULT '{}',
  cs_buckets INTEGER[] NOT NULL DEFAULT '{}',
  level_buckets INTEGER[] NOT NULL DEFAULT '{}',
  xp_buckets INTEGER[] NOT NULL DEFAULT '{}',
  kill_buckets INTEGER[] NOT NULL DEFAULT '{}',
  assist_buckets INTEGER[] NOT NULL DEFAULT '{}',
  death_buckets INTEGER[] NOT NULL DEFAULT '{}',
  jungle_buckets INTEGER[] NOT NULL DEFAULT '{}',
  physical_damage_buckets INTEGER[] NOT NULL DEFAULT '{}',
  physical_damage_taken_buckets INTEGER[] NOT NULL DEFAULT '{}',
  magic_damage_buckets INTEGER[] NOT NULL DEFAULT '{}',
  magic_damage_taken_buckets INTEGER[] NOT NULL DEFAULT '{}',
  true_damage_buckets INTEGER[] NOT NULL DEFAULT '{}',
  true_damage_taken_buckets INTEGER[] NOT NULL DEFAULT '{}',
  ward_placed_buckets INTEGER[] NOT NULL DEFAULT '{}',
  ward_killed_buckets INTEGER[] NOT NULL DEFAULT '{}',
  cc_time_buckets INTEGER[] NOT NULL DEFAULT '{}',
  gold_spent_buckets INTEGER[] NOT NULL DEFAULT '{}',
  turret_damage_buckets INTEGER[] NOT NULL DEFAULT '{}',
  objective_damage_buckets INTEGER[] NOT NULL DEFAULT '{}',
  jungle_camp_history JSONB NOT NULL DEFAULT '[]',
  win BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (riot_match_id, participant_id)
);

CREATE INDEX IF NOT EXISTS idx_participants_puuid ON participants (puuid);
CREATE INDEX IF NOT EXISTS idx_participants_champion ON participants (champion_id);
