/** Colonnes lane-vs-opponent ajoutées à `champion_vs_stats` (hors count_win/count_game). */
export const CHAMPION_VS_STATS_LANE_METRIC_COLUMNS = [
  "sum_kill_opponent_5min",
  "sum_kill_opponent_10min",
  "sum_kill_opponent_15min",
  "sum_death_by_opponent_5min",
  "sum_death_by_opponent_10min",
  "sum_death_by_opponent_15min",
  "sum_death_by_dive",
  "sum_kill_by_dive",
  "sum_kill_by_gank",
  "sum_death_by_gank",
  "sum_gold_difference_5min",
  "sum_gold_difference_10min",
  "sum_gold_difference_15min",
  "sum_gold_spent_5min",
  "sum_gold_spent_10min",
  "sum_gold_spent_15min",
  "sum_gold_spent_by_opponent_5min",
  "sum_gold_spent_by_opponent_10min",
  "sum_gold_spent_by_opponent_15min",
  "sum_gold_possessed_5min",
  "sum_gold_possessed_10min",
  "sum_gold_possessed_15min",
  "sum_gold_possessed_by_opponent_5min",
  "sum_gold_possessed_by_opponent_10min",
  "sum_gold_possessed_by_opponent_15min",
  "sum_cs_difference_5min",
  "sum_cs_difference_10min",
  "sum_cs_difference_15min",
  "sum_cs_5min",
  "sum_cs_10min",
  "sum_cs_15min",
  "sum_cs_opponent_5min",
  "sum_cs_opponent_10min",
  "sum_cs_opponent_15min",
  "sum_vision_score_difference_5min",
  "sum_vision_score_difference_10min",
  "sum_vision_score_difference_15min",
  "sum_vision_5min",
  "sum_vision_10min",
  "sum_vision_15min",
  "sum_vision_opponent_5min",
  "sum_vision_opponent_10min",
  "sum_vision_opponent_15min",
  "sum_level_5min",
  "sum_level_10min",
  "sum_level_15min",
  "sum_level_opponent_5min",
  "sum_level_opponent_10min",
  "sum_level_opponent_15min",
  "sum_xp_5min",
  "sum_xp_10min",
  "sum_xp_15min",
  "sum_xp_opponent_5min",
  "sum_xp_opponent_10min",
  "sum_xp_opponent_15min",
  "sum_have_legendary_item_first",
  "sum_opponent_have_legendary_item_first",
  "sum_buy_legendary_item_timestamp",
  "sum_opponent_buy_legendary_item_timestamp",
  "sum_have_boots_item_first",
  "sum_opponent_have_boots_item_first",
  "sum_buy_boots_item_timestamp",
  "sum_opponent_buy_boots_item_timestamp",
  "sum_have_boots_tier2_item_first",
  "sum_opponent_have_boots_tier2_item_first",
  "sum_buy_boots_tier2_item_timestamp",
  "sum_opponent_buy_boots_tier2_item_timestamp",
  "sum_consumable_item_bought",
  "sum_consumable_item_bought_by_opponent",
  "sum_kill_by_roaming",
  "sum_kill_by_roaming_by_opponent",
  "sum_death_by_roaming",
  "sum_death_by_roaming_by_opponent",
  "sum_first_tower",
  "sum_first_tower_by_opponent",
  "sum_turret_plate_taken",
  "sum_turret_plate_taken_by_opponent",
  "sum_drake_kill",
  "sum_drake_assist",
  "sum_drake_kill_by_opponent",
  "sum_drake_assist_by_opponent",
  "sum_void_kill",
  "sum_void_assist",
  "sum_void_kill_by_opponent",
  "sum_void_assist_by_opponent",
  "sum_herald_kill",
  "sum_herald_assist",
  "sum_herald_kill_by_opponent",
  "sum_herald_assist_by_opponent",
  "sum_objective_stolen",
  "sum_objective_stolen_by_opponent",
  "sum_kill_on_objective",
  "sum_kill_on_objective_by_opponent",
  "sum_death_on_objective",
  "sum_death_on_objective_by_opponent",
] as const

export type ChampionVsStatsLaneMetricColumn = (typeof CHAMPION_VS_STATS_LANE_METRIC_COLUMNS)[number]

export const CHAMPION_VS_STATS_LANE_METRIC_COLUMN_SET = new Set<string>(
  CHAMPION_VS_STATS_LANE_METRIC_COLUMNS,
)

/** Colonnes historiques + lane (ingestion upsert). */
export const CHAMPION_VS_STATS_LEGACY_METRIC_COLUMNS = [
  "sum_gold_earned",
  "sum_gold_spent",
  "sum_max_level_lead_lane_opponent",
  "sum_max_kill_deficit",
  "sum_more_enemy_jungle_than_opponent",
  "sum_max_cs_advantage_on_lane_opponent",
  "sum_vision_score_advantage_lane_opponent",
  "sum_laning_phase_gold_exp_advantage",
  "sum_early_laning_phase_gold_exp_advantage",
  "sum_physique_damage_done_to_champion_u15",
  "sum_magic_damage_done_to_champion_u15",
  "sum_true_damage_done_to_champion_u15",
  "sum_kill_u15",
  "sum_assist_u15",
  "sum_death_u15",
  "sum_vision_score_u15",
  "sum_shield_and_heal_u15",
  "sum_minions_killed_u15",
] as const

export const CHAMPION_VS_STATS_ALL_METRIC_COLUMNS = [
  ...CHAMPION_VS_STATS_LEGACY_METRIC_COLUMNS,
  ...CHAMPION_VS_STATS_LANE_METRIC_COLUMNS,
] as const
