/** @deprecated Import from rate-scheduler.js — réexport pour compatibilité. */
export {
  TARGET_PCT,
  DISCOVERY_SLOT_KEY,
  HYDRATION_SLOT_KEY,
  RANK_SLOT_KEY,
  MATCH_SLOT_KEY,
  SLOT_KEY,
  type RankSlotResult,
  totalTargetRatePerSec,
  discoveryTargetRatePerSec,
  hydrationTargetRatePerSec,
  rankTargetRatePerSec,
  advanceDripAccumulator,
  loadLuaScript,
  startDrip,
  stopDrip,
  waitForDiscoverySlot,
  waitForHydrationSlot,
  waitForRankSlot,
  waitForMatchSlot,
  waitForSlot,
  tryAcquireSlot,
  setGlobalRateLimitCooldown,
  createLuaRateLimiterForTests,
} from "./rate-scheduler.js";
