/** @deprecated Import from rate-scheduler.js — réexport pour compatibilité. */
export {
  TARGET_PCT,
  WINDOW_MS,
  SLOT_BUDGETS_REF,
  SLOT_TOKENS,
  SLOT_COSTS,
  slotBudgetForPipeline,
  totalSlotBudgetPer120s,
  tokenReleaseIntervalMs,
  jobReleaseIntervalMs,
  DISCOVERY_SLOT_KEY,
  HYDRATION_SLOT_KEY,
  RANK_SLOT_KEY,
  MATCH_SLOT_KEY,
  SLOT_KEY,
  type RankSlotResult,
  type SlotPipeline,
  totalTargetRatePerSec,
  discoveryTargetRatePerSec,
  hydrationTargetRatePerSec,
  rankTargetRatePerSec,
  advanceDripAccumulator,
  loadLuaScript,
  startDrip,
  stopDrip,
  waitForDiscoverySlot,
  waitForHydrationSlot,
  waitForRankSlot,
  acquireRankSlot,
  waitForMatchSlot,
  waitForSlot,
  tryAcquireSlot,
  setGlobalRateLimitCooldown,
  createLuaRateLimiterForTests,
} from "./rate-scheduler.js";
